# Generated by Django 3.2.16 on 2023-01-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_auto_20230114_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='might_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='needs_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='what_works',
            field=models.TextField(blank=True, null=True),
        ),
    ]
