# Generated by Django 3.2.16 on 2023-01-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0004_auto_20230114_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='body',
        ),
    ]
