# Generated by Django 3.2.16 on 2023-01-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0005_remove_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[(1, 'one_star'), (2, 'two_stars'), (3, 'three_stars'), (4, 'four_stars'), (5, 'five_stars')], max_length=200),
        ),
    ]
